// src/components/DarkModeToggle.vue
<script setup>
import { ref, onMounted, watch } from 'vue'
import { MoonIcon, SunIcon } from '@lucide/vue'

const darkMode = ref(false)

onMounted(() => {
  const stored = localStorage.getItem('site-dark-mode')
  darkMode.value = stored ? JSON.parse(stored) : false
  applyTheme(darkMode.value)
})

watch(darkMode, val => {
  applyTheme(val)
  localStorage.setItem('site-dark-mode', JSON.stringify(val))
})

function applyTheme(dark) {
  const html = document.documentElement
  html.classList.add('is-theme-transitioning')
  if (dark) {
    html.classList.add('dark')
  } else {
    html.classList.remove('dark')
  }
  setTimeout(() => html.classList.remove('is-theme-transitioning'), 150)
}
</script>

<template>
  <button
    :aria-label="darkMode ? 'Switch to light mode' : 'Switch to dark mode'"
    class="p-2 rounded-md border border-border bg-card hover:bg-accent transition-colors"
    @click="darkMode = !darkMode"
  >
    <SunIcon v-if="darkMode" class="h-5 w-5 text-foreground" />
    <MoonIcon v-else class="h-5 w-5 text-foreground" />
  </button>
</template>

// src/components/darkmodetoggle.jsx
import React from "react"
import Button from "react-bootstrap/Button"

import darkModeSvg from "../assets/dark_mode_white_24dp.svg"
import lightModeSvg from "../assets/light_mode_black_24dp.svg"

import "../styles/darkmodetoggle.css"

export default function Intro() {

    const [darkMode, setDarkMode] = React.useState(false);

    React.useEffect(() => {
        const json = localStorage.getItem("site-dark-mode");
        const currentMode = JSON.parse(json);
        if (currentMode) {
            setDarkMode(true);
        } else {
            setDarkMode(false);
        }
    }, []);

    React.useEffect(() => {
        if (darkMode) {
            document.body.classList.add("dark-theme");
            document.body.classList.remove("light-theme");
        } else {
            document.body.classList.add("light-theme");
            document.body.classList.remove("dark-theme");
        }
        const json = JSON.stringify(darkMode);
        localStorage.setItem("site-dark-mode", json);
    }, [darkMode]);

    return <Button variant={darkMode ? "light" : "dark"} className="btn-darkmode" onClick={() => setDarkMode(!darkMode)}>
        <img src={darkMode ? lightModeSvg : darkModeSvg} alt="Theme toggle" />
    </Button>
}
