// src/components/Intro.vue
<script setup>
import DarkModeToggle from './DarkModeToggle.vue'
import monkaW from '../assets/monkaw_sm.png'
</script>

<template>
  <div class="flex items-start gap-4">
    <div class="flex-1">
      <p class="text-muted-foreground">
        Use this simple tool to simulate StreamElements text-to-speech (TTS) voice messages for Twitch.
        Hear how a donation for your favorite streamer sounds like!
      </p>
      <p class="text-lg font-medium hidden sm:block">
        Chat we forgot <img :src="monkaW" alt="monkaW" class="inline-block align-middle" />
      </p>
    </div>
    <DarkModeToggle />
  </div>
</template>

// src/components/intro.jsx
import React from "react"
import Row from "react-bootstrap/Row"
import Col from "react-bootstrap/Col"
import Image from "react-bootstrap/Image"

import DarkModeToggle from "./darkmodetoggle"

import monkaW from "../assets/monkaw_sm.png"

export default function Intro() {
    return (
        <>
            <Row>
                <Col>
                    <p>Use this simple tool to simulate StreamElements text-to-speech (TTS) voice messages for Twitch. Hear how a donation for your favorite streamer sounds like!</p>
                    <div className="d-flex">
                        <div className="flex-grow-1">
                            <span className="lead d-none d-sm-block">Chat we forgot <Image src={monkaW} alt="monkaW" /></span>
                        </div>
                        <div>
                            <DarkModeToggle />
                        </div>
                    </div>
                </Col>
            </Row>
        </>
    )
}
